#!/bin/sh

read -r -d '' APPS_LIST << EndOfAppsList
com.apps.adrcotfas.goodtime
org.sufficientlysecure.keychain
com.oF2pks.applicationsinfo
org.videolan.vlc
com.simplemobiletools.gallery.pro
com.zeapo.pwdstore
org.totschnig.myexpenses
EndOfAppsList


fdroidcl update
echo "$APPS_LIST" | xargs -I "{}" fdroidcl install {}
