#!/bin/sh
connect()
{
	HEADPHONES_MAC=`echo exit | bluetoothctl | grep JBL | awk '{ print $4 }'`
	echo connect $HEADPHONES_MAC | bluetoothctl
}

disconnect()
{
	echo disconnect | bluetoothctl
}

VAL=`echo exit | bluetoothctl | grep exit | sed -r "s/\x1B\[([0-9]{1,3}((;[0-9]{1,3})*)?)?[m|K]//g" | cut -d '#' -f 1`

[ "$VAL" = "[bluetooth]" ] && connect || disconnect
