#!/bin/sh
BASENAME=`basename $1`
udisksctl mount -b /dev/disk/by-label/Transcend && \
	ffmpeg -i $1 -vcodec copy -acodec mp3 /media/$USER/Transcend/$BASENAME && \
	udisksctl unmount -b /dev/disk/by-label/Transcend
