#!/bin/sh

# HDMI
[ `xrandr | grep HDMI-2 | cut -d ' ' -f 2` = "connected" ] && \
	xrandr --output HDMI-2 --auto --primary && \
	xrandr --output eDP-1 --off && \
	xrandr --output DP-1 --off && \
	exit

# VGA
[ `xrandr | grep DP-1 | cut -d ' ' -f 2` = "connected" ] && \
	xrandr --output DP-1 --auto --primary && \
	xrandr --output eDP-1 --off && \
	xrandr --output HDMI-2 --off && \
	exit

# integrated
xrandr --output eDP-1 --auto --primary && \
xrandr --output DP-1 --off && \
xrandr --output HDMI-2 --off
