#!/bin/sh

HDMI="HDMI-1"
INTEGRATED="eDP-1"

# HDMI
[ `xrandr | grep $HDMI | cut -d ' ' -f 2` = "connected" ] && \
	xrandr --output $HDMI --auto --primary && \
	xrandr --output $INTEGRATED --off && \
	exit

# integrated
xrandr --output $INTEGRATED --auto --primary && \
xrandr --output $HDMI --off
